all:
	pdflatex assembler-generation.tex

clean:
	rm -f *.log
	rm -f assembler-generation.aux
	rm -f assembler-generation.log
	rm -f assembler-generation.nav
	rm -f assembler-generation.out
	rm -f assembler-generation.pdf
	rm -f assembler-generation.snm
	rm -f assembler-generation.toc
