all:
	pdflatex KIT-Folien-en.tex

clean:
	rm -f *.log
	rm -f KIT-Folien-en.aux
	rm -f KIT-Folien-en.log
	rm -f KIT-Folien-en.nav
	rm -f KIT-Folien-en.out
	rm -f KIT-Folien-en.pdf
	rm -f KIT-Folien-en.snm
	rm -f KIT-Folien-en.toc
