package compiler.main;

import java.io.BufferedInputStream;
import java.io.FileInputStream;
import java.io.IOException;

import org.apache.commons.cli.BasicParser;
import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.CommandLineParser;
import org.apache.commons.cli.HelpFormatter;
import org.apache.commons.cli.Options;
import org.apache.commons.cli.ParseException;

import compiler.StringTable;
import compiler.lexer.Lexer;
import compiler.lexer.Token;
import compiler.lexer.TokenType;

public class CompilerApp {

	private static final String LEXTEST = "lextest";

	public static void main(String args[]) throws IOException {
		Options options = new Options();
		options.addOption("h", "help", false, "print this message");
<<<<<<< HEAD
		options.addOption(null, LEXTEST, true, "print tokens generated by lexer");
=======
		options.addOption("l", LEXTEST, false, "print tokens generated by lexer");
>>>>>>> d747bff... added test to automatically verify all example programs

		CommandLineParser parser = new BasicParser();
		try {
			CommandLine cmd = parser.parse(options, args);
			if (cmd.hasOption("help"))
			{
				printHelp(options);
				return;
			}

<<<<<<< HEAD
			if (cmd.hasOption(LEXTEST)) {
				executeLexerTest(cmd.getOptionValue(LEXTEST));
				return;
			}
		} catch (ParseException e) {
			System.err.println("Wrong Command Line Parameters: " + e.getMessage());
		}
		printHelp(options);
		System.exit(1);
=======
            if (cmd.hasOption("lextest"))
            {
                MiniJavaCompiler.setOutputFormat(MiniJavaCompiler.OutputFormat.LEXER);
            }
            
            // @andreas-eberle  IMHO this class should only parse cmd options and
            // set correct values in compiler facade. the facade does compilation logic
            // including calling lexer, parser, etc.
            // (IMHO as in I insist - because we get points for software engineering)
            List args1 = cmd.getArgList();
            if (args1.size() != 1) {
                System.err.println( "Missing Filename / To Many Arguments");
                System.exit(-1);
            }
            
            // @andreas-eberle this is a facade for whole compiler
            // input: source-file name
            MiniJavaCompiler.compile((String) args1.get(0));

        } catch (Exception e) {
            System.err.println("Wrong Command Line Parameters: " + e.getMessage());
            System.exit(-1);
        }
>>>>>>> d747bff... added test to automatically verify all example programs
	}

	private static void executeLexerTest(String file) throws IOException {
		Lexer lexer = new Lexer(new BufferedInputStream(new FileInputStream(file)), new StringTable());

		Token token;
		do {
			token = lexer.getNextToken();
			System.out.println(token != null ? token.getTokenString() : "null");
		} while (token == null || token.getType() != TokenType.EOF);
	}

	private static void printHelp(Options options) {
		HelpFormatter formatter = new HelpFormatter();
		formatter.printHelp("compiler", options);
	}
}
